name: "wicked2nm integration tests"

on: workflow_call

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [tumbleweed, leap15.6]
    env:
      IMAGE: registry.opensuse.org/home/jcronenberg/github-ci/containers_${{ matrix.os }}/wicked2nm-${{ matrix.os }}:latest
    steps:
    - name: Git Checkout
      uses: actions/checkout@v3
    - uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: wicked2nm-${{ matrix.os }}-${{ hashFiles('Cargo.lock') }}
    - name: Pull container image
      run: podman pull $IMAGE
    - name: Build wicked2nm
      run: podman run --rm -it -e CARGO_TERM_COLOR=always -v .:/checkout $IMAGE bash -c "cd /checkout/ && cargo build"
    - name: Run integration tests
      run: podman run --rm -it -e CARGO_TERM_COLOR=always -v .:/checkout $IMAGE bash -c "/checkout/tests/test.sh"
