name: "migrate-wicked CI"

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  rust_ci:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
    - name: Git Checkout
      uses: actions/checkout@v3

    - name: Install toolchain
      run: rustup toolchain install stable

    - name: Install dependencies
      run: sudo apt install libclang-dev libpam-dev

    - name: Install cargo-binstall
      uses: taiki-e/install-action@v2
      with:
        tool: cargo-binstall

    - name: Install tarpaulin
      run: cargo-binstall --no-confirm cargo-tarpaulin

    - uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: rust-checks-tarpaulin-${{ hashFiles('Cargo.lock') }}

    - name: Unit tests
      run: cargo tarpaulin --color always --skip-clean --target-dir target/tarpaulin --out xml

    - name: Lint tests
      run: cargo fmt --all -- --check

    - name: Cargo clippy
      run: cargo clippy -- --no-deps -D warnings

    - name: Cargo clippy on unit tests
      run: cargo clippy -- --no-deps --cfg test -A unused_imports -D warnings

    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@v2
      with:
        format: cobertura
