name: "wicked2nm rust checks"

on: workflow_call

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
    - name: Git Checkout
      uses: actions/checkout@v3
    - name: Install toolchain
      run: rustup toolchain install stable
    - uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: wicked2nm-${{ hashFiles('Cargo.lock') }}
    - name: Lint tests
      run: cargo fmt --all -- --check

  clippy:
    runs-on: ubuntu-latest
    steps:
    - name: Git Checkout
      uses: actions/checkout@v3
    - name: Install toolchain
      run: rustup toolchain install stable
    - uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: wicked2nm-${{ hashFiles('Cargo.lock') }}
    - name: Cargo clippy
      run: cargo clippy -- --no-deps -D warnings
    - name: Cargo clippy on unit tests
      run: cargo clippy -- --no-deps --cfg test -A unused_imports -D warnings

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Git Checkout
      uses: actions/checkout@v3
    - name: Install toolchain
      run: rustup toolchain install stable
    - name: Install cargo-binstall
      uses: taiki-e/install-action@v2
      with:
        tool: cargo-binstall
    - name: Install tarpaulin
      run: cargo-binstall --no-confirm cargo-tarpaulin
    - uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: wicked2nm-tarpaulin-${{ hashFiles('Cargo.lock') }}
    - name: Unit tests
      run: cargo tarpaulin --color always --skip-clean --target-dir target/tarpaulin --out xml
    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@v2
      with:
        format: cobertura
